AWSTemplateFormatVersion: 2010-09-09

Parameters:
  MyBucketName:
    Description: Existing Bucket name
    Type: String

Resources: 
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      BucketName: !Sub "${MyBucketName}"
      WebsiteConfiguration:
        ErrorDocument: error.html
        IndexDocument: index.html

  LogicalID:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref 'WebsiteBucket'
      PolicyDocument:
        Statement:
        - Sid: PublicReadForGetBucketObjects
          Effect: Allow
          Principal: '*'
          Action: s3:GetObject
          Resource: !Join ['', ['arn:aws:s3:::', !Ref 'WebsiteBucket', /*]]
